# Enable Home Assistant API
api:

mdns:

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.${device_name}
    version: ${release_version}

ota:
 - platform: esphome
 - platform: web_server
   
logger:
  baud_rate: 0
  logs: 
    uptime.sensor: WARN
    homeassistant.sensor: WARN

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
#captive_portal: 

time:
  - platform: sntp
    id: sntp_time
    servers: !secret ntp_server_ip 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: False
  power_save_mode: HIGH
  output_power:  17dB
  #min_auth_mode: WPA2
  #use_psram: true
  manual_ip:
    static_ip: ${wifi_ip_address}
    gateway: 192.168.0.1
    subnet: 255.255.252.0
    dns1: 192.168.0.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}-fallback"
    password: !secret fallback_wifi_password

# Optional Web configuration entry
web_server:
  port: 80
  version: 2
  local: true

# Sensors for ESP version and WIFI information
text_sensor:
  # ESPHome version
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
    entity_category: "diagnostic"
    disabled_by_default: true
  # IP address and connected SSID
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
      entity_category: "diagnostic"
      disabled_by_default: true
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: "diagnostic"
      disabled_by_default: true
    power_save_mode:
      name: "Wifi Power Saving Setting"
      icon: mdi:power_save_mode
      entity_category: "diagnostic"
      disabled_by_default: true

sensor:
  # WiFi signal
  - platform: wifi_signal
    id: wifi_rssi
    name: "WiFi Signal"
    update_interval: 120s
    disabled_by_default: true
    entity_category: "diagnostic"
   # Uptime sensor.
  - platform: uptime
    name: Device_Uptime
    entity_category: "diagnostic"
    disabled_by_default: true
binary_sensor:
  - platform: status
    name: Device_Status
    entity_category: "diagnostic"
    disabled_by_default: true

    