<<: !include _base.yaml

substitutions:
  device_name: minibuddy-iboostpaper
  friendly_name:  Mini Buddy - iBoost Paper
  wifi_ip_address: 192.168.0.171
  release_version: '4.01'

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.${device_name}
    version: ${release_version}
  platformio_options:
    build_flags:
      - -D WIRELESS_PAPER
      - -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/SPI/src
      - -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/SD/src
      - -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/FS/src
    lib_deps:
      - heltec-eink-modules=https://github.com/todd-herbert/heltec-eink-modules
      - SPI
      - SD
      - FS
  on_boot:
    priority: -600
    then:
      - logger.log: "Booting ${friendly_name} (${release_version})"
      - lambda: |-
          id(myDisplay).screen_writeStatusLine("System Ready");
      - lambda: |-
          id(packet_count).publish_state(0);

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 8MB

logger:
  level: DEBUG
  baud_rate: 0
  logs:
    homeassistant.sensor: WARN
    sensor: WARN
    text_sensor: WARN
    esphWirelessPaper: DEBUG
    esphiBoost: DEBUG
    sx126x: INFO

external_components:
  - source:
      type: local
      path: "components"
    components:
      - esphWirelessPaper
      - esphiBoost
  - source: github://pr#10928
    components: [sx126x]
    refresh: 1h

spi:
  - id: spi_radio
    clk_pin: GPIO09
    mosi_pin: GPIO10
    miso_pin: GPIO11

sx126x:
  - id: sx126x_id
    hw_version: sx1262
    spi_id: spi_radio
    cs_pin: GPIO08
    rst_pin: GPIO12
    busy_pin: GPIO13
    dio1_pin: GPIO14
    modulation: FSK
    frequency: 868300000
    bandwidth: 312_0kHz
    bitrate: 99975
    deviation: 47600 #transmitter
    shaping: NONE  #transmitter
    payload_length: 0
    preamble_size: 4 #transmitter
    preamble_detect: 4
    crc_enable: true # (Optional, bool): Enables a 16 bit CRC calculation/check. Defaults to false.
    crc_inverted: false # (Optional, bool): Inverts the CRC if enabled. Defaults to true.
    crc_size : 2 #(Optional, int): Size of the CRC in bytes, either 1 or 2. Defaults to 2.
    crc_initial: 0xffff # (Optional, int): Initial CRC value as a hex integer. Defaults to 0x1D0F.
    crc_polynomial: 0x8005 # (Optional, int): CRC polynomial as a hex integer. Defaults to 0x1021.
    rf_switch: true
    pa_power: 20
    pa_ramp: 200us #transmitter
    tcxo_voltage:  1_8V
    tcxo_delay: 5ms
    sync_value:  [0xD3, 0x91, 0xD3, 0x91] 
    rx_start: true
    on_packet:
      then:
        - lambda: |-
            id(esphiBoost_id)->process_packet(x, rssi);

# control hardware screen and leds
switch:
  - platform: gpio
    pin: GPIO18
    name: "LED Light"
    id: led_switch
    icon: mdi:lightbulb
    restore_mode: RESTORE_DEFAULT_OFF

# display object
esphWirelessPaper:
  top_title: ${friendly_name} - ${release_version}
  id: myDisplay

# iBoost protocol handler using native sx126x radio
esphiBoost:
  id: esphiBoost_id
  radio_id: sx126x_id
  packet_count: packet_count
  last_packet: PacketLastReceived
  heating_mode: heating_mode
  heating_warn: heating_warn
  heating_power: heating_power
  heating_import: heating_import
  heating_boost_time: heating_boost_time
  heating_today: heating_today
  heating_yesterday: heating_yesterday
  heating_last_7: heating_last_7
  heating_last_28: heating_last_28
  heating_last_gt: heating_last_gt
  time_id: sntp_time
  rssi_iboost: rssi_iboost
  rssi_buddy: rssi_buddy
  rssi_sender: rssi_sender

# Some Status Text Sensors
text_sensor:
  - platform: template
    device_class: timestamp
    id: PacketLastReceived
    name: "Last Packet Received"
    disabled_by_default: True
    entity_category: "diagnostic"

  - platform: template
    id: heating_mode
    name: "Mode"
    icon: mdi:solar-power
  - platform: template
    id: heating_warn
    name: "Warn"
    icon: mdi:solar-power
    
sensor:
  - platform: uptime
    name: Uptime
    update_interval: 10s
    disabled_by_default: true

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
    disabled_by_default: true

  - platform: template
    name: Packet Count
    id: packet_count
    accuracy_decimals: 0
    disabled_by_default: true
    entity_category: "diagnostic"
  
  # iBoost sensors
  - platform: template
    id: heating_import
    name: "iBoost Import"
    unit_of_measurement: W
    accuracy_decimals: 0
    icon: mdi:solar-power
    
  - platform: template
    id: heating_power
    name: "iBoost Power"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    icon: mdi:solar-power

  - platform: template
    id: heating_today
    name: "iBoost Today"
    unit_of_measurement: Wh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power

  - platform: template
    id: heating_yesterday
    name: "iBoost Yesterday"
    unit_of_measurement: Wh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power

  - platform: template
    id: heating_last_7
    name: "iBoost Last 7 Days"
    unit_of_measurement: Wh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power

  - platform: template
    id: heating_last_28
    name: "iBoost Last 28 Days"
    unit_of_measurement: Wh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power

  - platform: template
    id: heating_last_gt
    name: "iBoost Total"
    unit_of_measurement: Wh
    accuracy_decimals: 0
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power

  - platform: template
    id: heating_boost_time
    name: "Manual Boost Time Remaining"
    unit_of_measurement: Min
    accuracy_decimals: 0
    device_class: duration
    icon: mdi:timer
  -
    platform: template
    id: rssi_iboost
    name: "RSSI iBoost"
    unit_of_measurement: dB
    accuracy_decimals: 1
    icon: mdi:signal
    disabled_by_default: true
    entity_category: "diagnostic"

  - platform: template
    id: rssi_buddy
    name: "RSSI Buddy"
    unit_of_measurement: dB
    accuracy_decimals: 1
    icon: mdi:signal
    disabled_by_default: true
    entity_category: "diagnostic"

  - platform: template
    id: rssi_sender
    name: "RSSI Sender"
    unit_of_measurement: dB
    accuracy_decimals: 1
    icon: mdi:signal
    disabled_by_default: true
    entity_category: "diagnostic"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Action Button"

button:
  - platform: template
    name: "Manual Boost START"
    id: BoostStart
    icon: "mdi:solar-power"
    on_press:
      then:
        - lambda: 'id(esphiBoost_id)->boost_start((uint8_t) id(boostTime).state);'

  - platform: template
    name: "Manual Boost CANCEL"
    id: BoostCancel
    icon: "mdi:solar-power"
    on_press:
      then:
        - lambda: 'id(esphiBoost_id)->boost_cancel();'

number:
  - platform: template
    name: "Manual Boost Time"
    id: boostTime
    icon: mdi:timer
    unit_of_measurement: Minutes
    optimistic: true
    initial_value: 15
    min_value: 0
    max_value: 120
    step: 15











